Repository universal-ember/reactiveweb, pull requests merged in 2024-01, with the labels that each got.

#26 Setup release-plan
  .changeset/config.json
  .github/workflows/ci.yml
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  CHANGELOG.md
  RELEASE.md
  package.json
  pnpm-lock.yaml
  tests/test-app/config/ember-try.js
Labels: internal

#30 Fix typo in ember-concurrency docs
  reactiveweb/src/ember-concurrency.ts
Labels: bug

#31 Add the helper from ember-resources
  reactiveweb/src/helper.ts
  tests/test-app/tests/utils/helper/js-test.ts
Labels: enhancement

#32 Fix issue with initial values in `keepLatest` and clarify behavior
  reactiveweb/src/keep-latest.ts
  tests/test-app/tests/utils/keep-latest/js-test.ts
  tests/test-app/tests/utils/keep-latest/rendering-test.gts
Labels: bug

#33 Remove note from ember-resources in the helper jsdoc
  reactiveweb/src/helper.ts
Labels: bug

#29 Setup glint in test app
  .github/workflows/ci.yml
  pnpm-lock.yaml
  tests/min-supportetd/package.json
  tests/test-app/app/templates/application.hbs
  tests/test-app/package.json
  tests/test-app/tests/utils/fps/rendering-test.gts
  tests/test-app/tsconfig.json
Labels: internal

#34 Add sync
  pnpm-lock.yaml
  reactiveweb/src/sync.ts
  tests/test-app/tests/utils/sync-test.gts
Labels: enhancement

#36 Add `@link`
  reactiveweb/package.json
  reactiveweb/src/-private/types.ts
  reactiveweb/src/link.ts
  reactiveweb/tsconfig.json
  tests/test-app/tests/utils/link-test.ts
Labels: enhancement

#37 CI: use --ignore-scripts during the setup job
  .github/workflows/ci.yml
Labels: internal

#39 Copy alternate `modifier` and `service` implementations from ember-resources
  pnpm-lock.yaml
  reactiveweb/package.json
  reactiveweb/src/-private/types.ts
  reactiveweb/src/resource/modifier/index.ts
  reactiveweb/src/resource/modifier/manager.ts
  reactiveweb/src/resource/service.ts
  reactiveweb/tsconfig.json
  tests/test-app/tests/resources/modifier-test.gts
  tests/test-app/tests/resources/service-test.gts
Labels: enhancement

#40 Split test apps into separate CI jobs.
  .github/workflows/ci.yml
  pnpm-lock.yaml
  tests/min-supported/.editorconfig
  tests/min-supported/.ember-cli
  tests/min-supported/.eslintignore
  tests/min-supported/.eslintrc.js
  tests/min-supported/.gitignore
  tests/min-supported/.prettierignore
  tests/min-supported/.prettierrc.js
  tests/min-supported/.stylelintignore
  tests/min-supported/.stylelintrc.js
  tests/min-supported/.template-lintrc.js
  tests/min-supported/.watchmanconfig
  tests/min-supported/README.md
  tests/min-supported/app/app.ts
  tests/min-supported/app/components/.gitkeep
  tests/min-supported/app/config/environment.d.ts
  tests/min-supported/app/controllers/.gitkeep
  tests/min-supported/app/helpers/.gitkeep
  tests/min-supported/app/index.html
  tests/min-supported/app/models/.gitkeep
  tests/min-supported/app/router.ts
  tests/min-supported/app/routes/.gitkeep
  tests/min-supported/app/styles/app.css
  tests/min-supported/app/templates/application.hbs
  tests/min-supported/config/ember-cli-update.json
  tests/min-supported/config/ember-try.js
  tests/min-supported/config/environment.js
  tests/min-supported/config/optional-features.json
  tests/min-supported/config/targets.js
  tests/min-supported/ember-cli-build.js
  tests/min-supported/package.json
  tests/min-supported/public/mockServiceWorker.js
  tests/min-supported/public/robots.txt
  tests/min-supported/testem.js
  tests/min-supported/tests/assertions.ts
  tests/min-supported/tests/index.html
  tests/min-supported/tests/msw.ts
  tests/min-supported/tests/test-helper.ts
  tests/min-supported/tests/utils/debounce
  tests/min-supported/tests/utils/ember-concurrency
  tests/min-supported/tests/utils/fps
  tests/min-supported/tests/utils/function
  tests/min-supported/tests/utils/keep-latest
  tests/min-supported/tests/utils/map
  tests/min-supported/tests/utils/remote-data
  tests/min-supported/tsconfig.json
  tests/min-supported/types/ember-data/types/registries/model.d.ts
  tests/min-supported/types/global.d.ts
  tests/min-supported/types/index.d.ts
Labels: internal

#41 Add multiple entrypoints to the api docs
  docs/typedoc.config.json
Labels: documentation

#42 Change the description of the npm package
  reactiveweb/package.json
Labels: breaking

#43 Fix import paths in inline docs
  reactiveweb/src/resource/modifier/index.ts
  reactiveweb/src/resource/service.ts
Labels: bug

#44 Do not allow deprecations to exist
  pnpm-lock.yaml
  reactiveweb/src/function.ts
  tests/min-supported/package.json
  tests/test-app/app/app.ts
  tests/test-app/app/deprecation-workflow.ts
  tests/test-app/package.json
Labels: internal

#50 Fix in-editor docs
  reactiveweb/src/helper.ts
  reactiveweb/src/link.ts
Labels: bug

#51 Use correct import paths
  tests/test-app/tests/utils/helper/js-test.ts
  tests/test-app/tests/utils/link-test.ts
Labels: internal

#52 Upgrade test-apps to ember-resources@6.5.1 to test against deprecations
  pnpm-lock.yaml
  tests/min-supported/package.json
  tests/test-app/package.json
Labels: internal

#53 Update compilation tools, now using decorator-transforms
  pnpm-lock.yaml
  reactiveweb/babel.config.json
  reactiveweb/package.json
Labels: internal

#54 Refactor the map util to not be a resource, it never needed to be
  .github/workflows/ci.yml
  reactiveweb/src/map.ts
  tests/test-app/tests/utils/map/js-test.ts
Labels: enhancement

#55 Update the service implementation to not require knowledge of a specific class-based resource implementation
  pnpm-lock.yaml
  reactiveweb/src/resource/service.ts
  tests/min-supported/package.json
  tests/test-app/package.json
  tests/test-app/tests/resources/service-test.gts
Labels: enhancement

#56 Upgrade eslint-plugin-ember
  pnpm-lock.yaml
  reactiveweb/package.json
  tests/min-supported/.eslintrc.js
  tests/min-supported/package.json
  tests/test-app/.eslintrc.js
  tests/test-app/package.json
Labels: internal

#45 Migrate `trackedTask`'s implementation to use function-based resources
  pnpm-lock.yaml
  reactiveweb/package.json
  reactiveweb/src/ember-concurrency.ts
  tests/min-supported/package.json
  tests/test-app/package.json
Labels: enhancement

#57 docs: correct import lines in code example
  reactiveweb/src/keep-latest.ts
  tests/test-app/tests/resources/modifier-test.gts
  tests/test-app/tests/resources/service-test.gts
  tests/test-app/tests/utils/function/rendering-test.gts
Labels: bug

#60 Auto lintfix
  .github/workflows/ci.yml
  .github/workflows/pr-fixer.yml
Labels: internal

#63 Reduce CI time
  .github/workflows/ci.yml
  .github/workflows/pr-fixer.yml
Labels: internal

#69 Add new util: Throttle
  reactiveweb/src/throttle.ts
  tests/test-app/tests/utils/throttle-test.gts
Labels: enhancement

#71 Update renovate config
  .github/renovate.json5
Labels: internal
